### ISSUE TITLE
pytest-html-reporter throws error while using with pytest-html plugin

### ISSUE THREAD

**Issue by tarunmudgal** [prashanth-sams/pytest-html-reporter#131]
Below was the traceback observed-

```[03-09-2020 06:48:14 PM] [INFO] [test_runner.py] [249]: [run_pytest] starting pytest test cases execution at: 03Sep2020_18:48:14.636870
Traceback (most recent call last):
  File "test_runner.py", line 442, in <module>
    pytest_status = run_pytest(pytest_cmdline)
  File "test_runner.py", line 251, in run_pytest
    status = pytest.main(*args, **kwargs)
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/_pytest/config/__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/_pytest/config/__init__.py", line 994, in _preparse
    self.known_args_namespace = ns = self._parser.parse_known_args(
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/_pytest/config/argparsing.py", line 146, in parse_known_args
    return self.parse_known_and_unknown_args(args, namespace=namespace)[0]
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/_pytest/config/argparsing.py", line 156, in parse_known_and_unknown_args
    optparser = self._getparser()
  File "/Users/mtarun/vmware/code/venv_3/lib/python3.8/site-packages/_pytest/config/argparsing.py", line 120, in _getparser
    arggroup.add_argument(*n, **a)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --html: conflicting option string: --html
```

**Comment by prashanth-sams** [comment]
@tarunmudgal fixed in `0.1.8`. Going forward the cli will be `--html-report`
